### ISSUE TITLE
Remove the SWAP space on the login (and bastion nodes)

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#34] opened 2023-03-29 16:31 UTC
Probably somewhere in the terraform is my guess.  I'd rather processes just die then grind the system to a halt trying to perform a failing operation.

**Comment by andriy-safe-ai** [comment] 2023-06-20 17:22
Duplicate of #38. Closing.

**Closed by andriy-safe-ai** 2023-06-20 17:22 UTC
