### ISSUE TITLE
copy node_ordering_by_rack.py

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#25] opened 2023-03-14 16:38 UTC
```
TASK [rack-aware : copy node_ordering_by_rack.py] ******************************
fatal: [inst-e6vvd-watch-tower]: FAILED! => changed=false
checksum: 5c124431f0167c446ee6f7cb89d99c4918d594a6
gid: 1000
group: opc
mode: '0664'
msg: chgrp failed
owner: opc
path: /opt/oci-hpc/bin/node_ordering_by_rack.py
size: 3005
state: file
uid: 1000
fatal: [inst-e4wkl-watch-tower]: FAILED! => changed=false
checksum: 5c124431f0167c446ee6f7cb89d99c4918d594a6
gid: 1000
group: opc
mode: '0664'
msg: chgrp failed
owner: opc
path: /opt/oci-hpc/bin/node_ordering_by_rack.py
size: 3005
state: file
uid: 1000


TASK [rack-aware : copy node_ordering_by_rack.py] ******************************
fatal: [inst-e6vvd-watch-tower]: FAILED! => changed=false
checksum: 5c124431f0167c446ee6f7cb89d99c4918d594a6
gid: 1000
group: opc
mode: '0664'
msg: chgrp failed
owner: opc
path: /opt/oci-hpc/bin/node_ordering_by_rack.py
size: 3005
state: file
uid: 1000
...ignoring
```

**Comment by andriy-safe-ai** [comment] 2023-07-31 22:29
@steven-basart 

Would you be able to explain what is going on here please?

**Comment by steven-basart** [comment] 2023-07-31 22:57
Old bug that I think has been fixed (not by me probably during one of the upgrades). Wherever I encounter a bug I make an issue. This was one of them. It occurred the rack aware role.

**Comment by andriy-safe-ai** [comment] 2023-07-31 23:36
@steven-basart 

Any means to reproduce or can we close?

**Comment by steven-basart** [comment] 2023-08-19 13:05
To reproduce we just need to see which play book calls the "rack-aware" task and see if it succeeds now.

**Comment by andriy-safe-ai** [comment] 2023-09-22 16:18
@steven-basart 

This task is run by the resize script. We've run resize multiple times since March when this issue was created. I've also noticed that the permissions in the rack-aware role have been changed from `644` to `755`. 

I created a simple playbook to execute the `rack-aware` role to test whether the copy play works correctly:
```
- hosts: bastion
  roles:
    - rack-aware
```
The playbook ran successfully:
```
PLAY RECAP *********************************************************************
watch-tower-bastion        : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
```

I think we are good to close this issue.

**Comment by andriy-safe-ai** [comment] 2023-09-22 16:21
@steven-basart 

I also ran the same playbook but on all compute nodes instead of just the bastion node:
```
PLAY RECAP *********************************************************************
inst-1izto-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-3lkhl-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-4550h-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-4aqno-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-7vnv6-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-aa2un-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-alr3c-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-bmccd-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-cpqls-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-e6vvd-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-encjw-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-evoyb-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-fnbev-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-fwhck-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-gp7wn-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-hgqwx-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-hsfgo-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-mdqbh-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-necvh-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-nfanw-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-qj9qc-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-rbxtc-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-rk4hy-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-u90mk-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-ul7as-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-umizk-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-unr7l-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-wzlds-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-xydnk-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-ysctj-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
inst-yum8n-watch-tower     : ok=5    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
```

**Comment by andriy-safe-ai** [comment] 2023-09-27 16:37
@steven-basart 

TASK [rack-aware : copy node_ordering_by_rack.py] **********************************************************************************************************************************************************************************************
ok: [inst-cpqls-watch-tower]
ok: [inst-alr3c-watch-tower]
ok: [inst-unr7l-watch-tower]
ok: [inst-umizk-watch-tower]
ok: [inst-ysctj-watch-tower]
ok: [inst-encjw-watch-tower]
ok: [inst-ul7as-watch-tower]
ok: [inst-qj9qc-watch-tower]
ok: [inst-fwhck-watch-tower]
ok: [inst-gp7wn-watch-tower]
ok: [inst-xydnk-watch-tower]
ok: [inst-4550h-watch-tower]
ok: [inst-hgqwx-watch-tower]
ok: [inst-rk4hy-watch-tower]
ok: [inst-4aqno-watch-tower]
ok: [inst-evoyb-watch-tower]
ok: [inst-rbxtc-watch-tower]
ok: [inst-fnbev-watch-tower]
ok: [inst-wzlds-watch-tower]
ok: [inst-yum8n-watch-tower]
ok: [inst-7vnv6-watch-tower]
ok: [inst-u90mk-watch-tower]
ok: [inst-nfanw-watch-tower]
ok: [inst-mdqbh-watch-tower]
ok: [inst-e6vvd-watch-tower]
ok: [inst-3lkhl-watch-tower]
ok: [inst-1izto-watch-tower]
ok: [inst-hsfgo-watch-tower]
ok: [inst-bmccd-watch-tower]
ok: [inst-necvh-watch-tower]

**Comment by steven-basart** [comment] 2023-09-27 16:38
LGTM

**Comment by andriy-safe-ai** [comment] 2023-09-27 16:38
Resolved. Closing.

**Closed by andriy-safe-ai** 2023-09-27 16:38 UTC
