### ISSUE TITLE
Add har file to Oracle ticket for Removing APAC

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#66] opened 2023-04-28 04:14 UTC
Add David Chen so he can add it and close the ticket.

**Comment by steven-basart** [comment] 2023-04-28 14:26
SR: 3-32657279181

**Comment by trent-safe-ai** [comment] 2023-05-16 13:33
This ticket is complex in that the apps that the domain thinks its using are related to log analytics. need to disable/remove the s3 related to that domain and delete it.

**Comment by trent-safe-ai** [comment] 2023-06-15 18:12
spoke to oracle sr again- they will escalate internally.

**Comment by trent-safe-ai** [comment] 2023-07-10 14:20
this ticket is still in flight- Gaurav has escalated and we may have Ruhzu (who initially created the domain) to log on to our tenancy and try and delete the domain.

**Comment by trent-safe-ai** [comment] 2023-08-03 00:51
this perpetually goes round and round with Oracle- they can't fix it- nor find the cause. so in the icebox this will stay.

**Comment by trent-safe-ai** [comment] 2023-08-10 14:34
Finally removed- closing SR soon. Internal devs had to hard remove all the apps int he domain.
![sr-9181-1.JPG](https://images.zenhubusercontent.com/64834715de9d9e4a2f2a1091/42054bb6-5c27-4cbc-a656-5f34a66a7bc7)![sr-9181-2.JPG](https://images.zenhubusercontent.com/64834715de9d9e4a2f2a1091/172b828c-baa8-45e5-8ed0-fe468fb5b815)![sr-9181-3.JPG](https://images.zenhubusercontent.com/64834715de9d9e4a2f2a1091/51faede1-4aaa-4dcf-879c-88d3e3db7a32)

**Closed** 2023-08-10 14:35 UTC
